// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/search": {
            "post": {
                "description": "Perform a Google search using SerpAPI and retrieve organic results with advanced filtering options",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search Google for leads",
                "parameters": [
                    {
                        "description": "Search parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful search results",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ErrorResponse": {
            "description": "Error response returned when request fails",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message describing what went wrong",
                    "type": "string",
                    "example": "Key: 'SearchRequest.Q' Error:Field validation for 'Q' failed on the 'required' tag"
                }
            }
        },
        "dto.SearchRequest": {
            "description": "Search request parameters for Google search",
            "type": "object",
            "required": [
                "location",
                "q"
            ],
            "properties": {
                "exclude_domains": {
                    "description": "List of domains to exclude from search results",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "instagram.com",
                        "linkedin.com",
                        "facebook.com"
                    ]
                },
                "gl": {
                    "description": "Country code for search results",
                    "type": "string",
                    "example": "br"
                },
                "hl": {
                    "description": "Language code for search results",
                    "type": "string",
                    "example": "pt-br"
                },
                "location": {
                    "description": "Location for geo-targeted search",
                    "type": "string",
                    "example": "Recife"
                },
                "num": {
                    "description": "Total number of results to return (default: 10, max: 100). Multiple pages will be fetched automatically if needed.",
                    "type": "integer",
                    "example": 50
                },
                "q": {
                    "description": "Search query string",
                    "type": "string",
                    "example": "escritório de contabilidade"
                },
                "start": {
                    "description": "Result offset for pagination (default: 0)",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "handlers.OrganicResult": {
            "description": "A single organic search result from Google",
            "type": "object",
            "properties": {
                "displayed_link": {
                    "description": "Displayed URL shown in search results",
                    "type": "string",
                    "example": "www.example.com.br"
                },
                "extensions": {
                    "description": "Additional extensions like ratings text",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Classificação",
                        "10/10 (3)"
                    ]
                },
                "link": {
                    "description": "URL of the search result",
                    "type": "string",
                    "example": "https://www.example.com.br/"
                },
                "position": {
                    "description": "Position of the result in the search results",
                    "type": "integer",
                    "example": 1
                },
                "rating": {
                    "description": "Rating score if available",
                    "type": "number",
                    "example": 4.8
                },
                "reviews": {
                    "description": "Number of reviews if available",
                    "type": "integer",
                    "example": 245
                },
                "scrape_error": {
                    "description": "ScrapeError contains error message if scraping failed",
                    "type": "string"
                },
                "scraped_content": {
                    "description": "ScrapedContent is the markdown content scraped from the website homepage (populated by FirecrawlHandler)",
                    "type": "string"
                },
                "sitelinks": {
                    "description": "Sitelinks associated with this result",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handlers.Sitelinks"
                        }
                    ]
                },
                "snippet": {
                    "description": "Snippet/description of the search result",
                    "type": "string",
                    "example": "Precisa de um contador em Recife? Oferecemos serviços de contabilidade, abertura de empresa e muito mais."
                },
                "title": {
                    "description": "Title of the search result",
                    "type": "string",
                    "example": "Escritório de Contabilidade em Recife - Contador em Recife"
                }
            }
        },
        "handlers.Pagination": {
            "description": "Pagination information for search results",
            "type": "object",
            "properties": {
                "current": {
                    "description": "Current page number",
                    "type": "integer",
                    "example": 1
                },
                "next": {
                    "description": "URL for the next page of results",
                    "type": "string",
                    "example": "https://serpapi.com/search.json?engine=google\u0026start=10"
                }
            }
        },
        "handlers.SearchResponse": {
            "description": "Response containing organic search results and pagination info",
            "type": "object",
            "properties": {
                "organic_results": {
                    "description": "List of organic search results",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.OrganicResult"
                    }
                },
                "pages_fetched": {
                    "description": "Number of pages fetched to get these results",
                    "type": "integer",
                    "example": 5
                },
                "serpapi_pagination": {
                    "description": "Pagination information (for the last page fetched)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handlers.Pagination"
                        }
                    ]
                },
                "total_results": {
                    "description": "Total number of results returned",
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "handlers.Sitelink": {
            "description": "Inline sitelink with title and URL",
            "type": "object",
            "properties": {
                "link": {
                    "description": "URL of the sitelink",
                    "type": "string",
                    "example": "https://example.com/contact"
                },
                "title": {
                    "description": "Title of the sitelink",
                    "type": "string",
                    "example": "Contact Us"
                }
            }
        },
        "handlers.Sitelinks": {
            "description": "Container for inline sitelinks",
            "type": "object",
            "properties": {
                "inline": {
                    "description": "List of inline sitelinks",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Sitelink"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Lead Gen Worker API",
	Description:      "A high-performance REST API service for scraping Google search results using SerpAPI. Designed for lead generation workflows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
